### ISSUE TITLE
[bug]: CLI crashes replacing old project files

### ISSUE THREAD

**Issue by craiglabenz** [invertase/flutterfire_cli#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

11.1.0

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.9.0-0.2.pre, on macOS 12.6 21G115 darwin-arm64,
    locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.77.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.

### Description

I deleted an old Firebase project and am regenerating from scratch. My project name is unchanged, but all the long random IDs are of course new. The CLI registered my 3 Firebase apps (iOS, Android, and macOS) successfully, then crashed when placing the `google-services.json` files.

### Steps to reproduce

$ flutterfire configure --project=<project_name>
i Found 1 Firebase projects. Selecting project <project_name>.
? Which platforms should your configuration support (use arrow keys & space to s
✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios, macos
i Firebase android app <reverse_domain> is not registered on Firebase project <project_name>.
i Registered a new Firebase android app on Firebase project <project_name>.
i Firebase ios app <reverse_domain> registered.
i Firebase macos app <reverse_domain> is not registered on Firebase project <project_name>.
i Registered a new Firebase macos app on Firebase project <project_name>.
? Generated FirebaseAppID file ~/Dev/washday/washday-app/macos/firebase_app_id_file.json already exists, do you want to override it? (y/n) › ye
? Generated FirebaseAppID file ~/washday/washday-app/macos/firebase_app_id_file.json already exists, do you want to override it? (y/n) › ye
✔ Generated FirebaseAppID file ~/Dev/washday/washday-app/macos/firebase_app_id_file.json already exists, do you want to override it? · yes
? The google-services.json file already exists but for a different Firebase project (<old_name>). Do you want to replace it with Firebase project <project_name>
? The google-services.json file already exists but for a different Firebase project (<old_name>). Do you want to replace it with Firebase project <project_name>
✔ The google-services.json file already exists but for a different Firebase project (<old_name>). Do you want to replace it with Firebase project <project_name>? · yes
Unhandled exception:
Exception: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:540:11)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#2      main (file:///Users/<username>/.pub-cache/hosted/pub.dev/flutterfire_cli-0.2.7/bin/flutterfire.dart:57:5)
<asynchronous suspension>

### Expected behavior

The CLI should have successfully replaced the old config files and completed running normally.

**Comment by craiglabenz** [comment]
Got around this by deleting (my somehow empty?) and re-downloading `google-services.json` file and then running `sudo gem install xcodeproj` as indicated in #30.
