### ISSUE TITLE
[bug]:  'YamlMap' is not a subtype of type 'String?'

### ISSUE THREAD

**Issue by arjun-wm-wrk** [invertase/flutterfire_cli#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

12.5.1

### Flutter Doctor Output

Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2134], locale en-IN)
    • Flutter version 3.13.1 on channel stable at C:\Users\Public\Softwares\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (33 hours ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.96
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.54

[√] Network resources
    • All expected network resources are available.

### Description

After installing firebase tools, logiing in to my firebase account and running the command "flutterfire configure" in my project, I get he following error - 

type 'YamlMap' is not a subtype of type 'String?'
#0      JsonParser.mapEntries.<anonymous closure> (package:pubspec/src/json_utils.dart:129:30)
#1      MapBase.forEach (dart:collection/maps.dart:35:13)
#2      JsonParser.mapEntries (package:pubspec/src/json_utils.dart:128:7)
#3      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:114:22)
#4      PubSpec.loadFile (package:pubspec/src/pubspec.dart:128:15)
<asynchronous suspension>
#5      Package.load (package:flutterfire_cli/src/common/package.dart:54:21)
<asynchronous suspension>
#6      FlutterApp.load (package:flutterfire_cli/src/flutter_app.dart:39:21)
<asynchronous suspension>
#7      main (file:///C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/flutterfire_cli-0.2.6+1/bin/flutterfire.dart:56:24)
<asynchronous suspension>
Unhandled exception:
type 'YamlMap' is not a subtype of type 'String?'
#0      JsonParser.mapEntries.<anonymous closure> (package:pubspec/src/json_utils.dart:129:30)
#1      MapBase.forEach (dart:collection/maps.dart:35:13)
#2      JsonParser.mapEntries (package:pubspec/src/json_utils.dart:128:7)
#3      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:114:22)
#4      PubSpec.loadFile (package:pubspec/src/pubspec.dart:128:15)
<asynchronous suspension>
#5      Package.load (package:flutterfire_cli/src/common/package.dart:54:21)
<asynchronous suspension>
#6      FlutterApp.load (package:flutterfire_cli/src/flutter_app.dart:39:21)
<asynchronous suspension>
#7      main (file:///C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/flutterfire_cli-0.2.6+1/bin/flutterfire.dart:56:24)
<asynchronous suspension>

### Steps to reproduce

run flutterfire configure

### Expected behavior

The command needs to configure the project for firebase

**Comment by russellwheatley** [comment]
@arjun-wm-wrk try the latest dev release, it is a lot more stable:

```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite

```

**Comment by russellwheatley** [comment]
Closing out as the issue is stale.
