### ISSUE TITLE
Cannot configure firebase

### ISSUE THREAD

**Issue by luis-cruzt** [invertase/flutterfire_cli#2]
When running the command ```flutterfire configure``` i'm getting the following error:

```Unhandled exception:
Null check operator used on a null value
#0      ConfigCommand._selectFirebaseProject.<anonymous closure> (package:flutterfire_cli/src/commands/config.dart:152:57)
#1      _SpinnerState.render (package:interact/src/spinner.dart:105:37)
#2      State.setState (package:interact/src/framework/state.dart:45:5)
#3      _SpinnerState.interact.<anonymous closure> (package:interact/src/spinner.dart:125:9)
#4      main (file:///Users/user/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.0+2/bin/flutterfire.dart:37:37)
<asynchronous suspension>```

**Comment by Salakar** [comment]
Can you try version `0.1.0+3` please and let me know if you have the same issue, thanks

**Comment by Salakar** [comment]
Have confirmed on my Windows machine (where I was able to replicate, but could not replicate on macos strangely) that this is now fixed.
