### ISSUE TITLE
[bug]:  Configure fails after renaming iOS Project

### ISSUE THREAD

**Issue by vincekruger** [invertase/flutterfire_cli#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

12.5.2

### Flutter Doctor Output

```bash
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale en-ES)
    • Flutter version 3.13.2 on channel stable at /Users/xxx/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (13 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] VS Code (version 1.79.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.66.0

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Description

Failed to configure my project after renaming the iOS Project.

```
i Found 18 Firebase projects.                                                                                                                                                       
✔ Select a Firebase project to configure your Flutter application with · firebase-project-c2e99 (Testing App)                                                                      
✔ Which platforms should your configuration support (use arrow keys & space to select)? · ios                                                                                       
✔ Which ios bundle id do you want to use for this configuration, e.g. 'com.example.app'? · com.example.project                                                        
i Firebase ios app com.example.project is not registered on Firebase project firebase-project-12345.                                                                    
i Registered a new Firebase ios app on Firebase project firebase-project-12345.                                                                                                       
Unhandled exception:
Exception: /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:110:in `open': [Xcodeproj] Unable to open `/{project-path}/ios/Runner.xcodeproj` because it doesn't exist. (RuntimeError)
        from -e:8:in `<main>'

#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:540:11)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#2      main (file:///Users/vincekruger/.pub-cache/hosted/pub.dev/flutterfire_cli-0.2.7/bin/flutterfire.dart:57:5)
<asynchronous suspension>
```

### Steps to reproduce

1. Create a new project
2. Follow the steps outlined here: https://github.com/flutter/flutter/pull/124533
3. Add firebase_core package
4. Update Podfiles outlined here: https://github.com/flutter/flutter/pull/124533#issuecomment-1708522367
5. Run `flutterfire configure`

### Expected behavior

Should create the configuration files

**Comment by russellwheatley** [comment]
Previously, it was not possible to rename your iOS Flutter project, this is not the case anymore and is being tracked on this issue: https://github.com/invertase/flutterfire_cli/issues/217
