### ISSUE TITLE
FormatException: Unexpected character when calling flutterfire configure

### ISSUE THREAD

**Issue by prabel** [invertase/flutterfire_cli#27]
After calling `flutterfire configure` commend, I'm always getting error
```
⠸ Fetching available Firebase projects...
Unhandled exception:
FormatException: Unexpected character (at character 1)
{
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:506:36)
#5      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)
<asynchronous suspension>
#6      getProjects (package:flutterfire_cli/src/firebase.dart:114:7)
<asynchronous suspension>
#7      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:159:24)
<asynchronous suspension>
#8      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:227:37)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     main (file:///Users/xxxx/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.1+2/bin/flutterfire.dart:34:5)
<asynchronous suspension>
```

I'm using Flutter version 2.8.1
```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (13 days ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

**Comment by flypsyco** [comment]
I had a same issue and resolve it.

The first issue I got was 
"i Found 0 Firebase projects. Selecting project liveasy-1. FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command. COMMAND: firebase --version ERROR: The FlutterFire CLI currently requires the official Firebase CLI to also be installed, see https://firebase.google.com/docs/cli#install_the_firebase_cli for how to install it."

and I solved it by 
1. changing the name of firebase-tools-instance.exe to firebase.exe
2. placing the firebase.exe at the root folder of my flutter project
The exe file was downloaded from https://firebase.google.com/docs/cli#install-cli-windows
#reference: https://stackoverflow.com/questions/70410843/firebasecommandexception-an-error-occured-on-the-firebase-cli-when-attempting-t

The next step, I got the same issue with you

```
C:\yp0215\01_private\01_study\app\fbtest>dart pub global activate flutterfire_cli
Package flutterfire_cli is currently active at version 0.1.1+2.
Resolving dependencies...
The package flutterfire_cli is already activated at newest available version.
To recompile executables, first run `global deactivate flutterfire_cli`.
Installed executable flutterfire.
Activated flutterfire_cli 0.1.1+2.

C:\yp0215\01_private\01_study\app\fbtest>flutterfire configure
⠋ Fetching available Firebase projects...
Unhandled exception:
FormatException: Unexpected character (at character 1)
#
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:506:36)
#5      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)
<asynchronous suspension>
#6      getProjects (package:flutterfire_cli/src/firebase.dart:114:7)
<asynchronous suspension>
#7      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:159:24)
<asynchronous suspension>
#8      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:227:37)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     main (file:///C:/Users/yp0215.hong/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.1+2/bin/flutterfire.dart:34:5)
<asynchronous suspension>

```


The solution that I found is run the command of "dart pub global activate flutterfire_cli" and "flutterfire configure" at the firebase shell.


```
C:\yp0215\01_private\01_study\app\fbtest>firebase
########################################################################################################################################################################################################################################

     Welcome to...
   ######## #### ########  ######## ########     ###     ######  ########  ##
   ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##        ##
   ######    ##  ########  ######   ########  #########  ######  ######    ##
   ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##       
   ##       #### ##     ## ######## ########  ##     ##  ######  ########  ##
 

########################################################################################################################################################################################################################################

~ Let's make sure your Firebase CLI is ready...
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (C:\snapshot\firepit\welcome.js:115:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)

> dart pub global activate flutterfire_cli
Package flutterfire_cli is currently active at version 0.1.1+2.
Resolving dependencies...
The package flutterfire_cli is already activated at newest available version.
To recompile executables, first run `global deactivate flutterfire_cli`.
Installed executable flutterfire.
Activated flutterfire_cli 0.1.1+2.

> flutterfire configure
i Found 2 Firebase projects.
? Select a Firebase project to configure your Flutter application with ›
❯ fbtest-6c9d3 (fbtest)
```


I don't know it's the right solution, but I can make the firebase_options.dart file.

My environment is windows10 and I use android studio

'''
C:\yp0215\01_private\01_study\app\fbtest>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1415], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (2 available)

• No issues found!

'''

**Comment by prabel** [comment]
Thanks for the tips @flypsyco 
In my case updating firebase cli
```
curl -sL firebase.tools | upgrade=true bash
```

and then calling 
```
firebase login --reauth
```

resolved all issues 🎉

**Comment by HossamTarek-bits** [comment]
if someone tried either @flypsyco or @prabel solutions and it didn't work try installing firebase using npm instead of downloading the standalone binary it worked for me

**Comment by lagagne72** [comment]
in my case, the issue was an old  firebase-tools version. 
fixed it with ` npm install -g firebase-tools`, and then `flutterfire configure` worked like a charm.

**Comment by emmanuel1997-bit** [comment]
> > dart pub global activate flutterfire_cli
Access is denied.

**Comment by emmanuel1997-bit** [comment]
how  can  i  fix  it

**Comment by vincekruger** [comment]
On mac run `sudo gem install xcodeproj` and then configure everything again.

**Comment by fakfa19** [comment]
> On mac run `sudo gem install xcodeproj` and then configure everything again.

It worked for me!

**Comment by mahammadbakr** [comment]
> sudo gem install xcodeproj

thank you mate, it worked!

**Comment by cybex-dev** [comment]
Had a similar issue - suggestions from [stackoverflow](https://stackoverflow.com/a/74385277/4628115) and [lagagne72](https://github.com/invertase/flutterfire_cli/issues/27#issuecomment-1253300234) resolved this problem.

I'm using `google_sign-in` w/ `firebase_auth` for "Sign in with Firebase". Upon logging in and running:
```dart
_firebaseAuth.signInWithCredential(googleAuthCredential)
```
I get an error thrown: 
```dart
{
  code: "api-key-expired.-please-renew-the-api-key.",
  message: "Error",
  ...
}
```

**Tried**
- `firebase login --reauth`, unsuccessful.
- `npm install -g firebase-tools`, followed by `firebase login --reauth`, unsuccessful

**Solution** (for my particular case)
Completely relogging
-  `firebase logout`, ` firebase login`, then finally `flutterfire configure`.

No more authentication error.

**Comment by pablowsky** [comment]
Delete `google-services.json` file and try again

**Comment by BaptisteLecat** [comment]
Same as @lcw99 my google-services.json was empty. So I just removed it and re run the flutterfire configure command.

**Comment by brand17** [comment]
I installed nodejs with nvm and then deleted firebase.exe from project folder (I copied it there before).

**Comment by cybex-dev** [comment]
If anyone

> Delete `google-services.json` file and try again

If anyone comes across this issue with no prior solution(s) - the quoted solution worked.

I used firebase-tools from `npm`, and standalone installer but neither worked. In installed (updated) xcodeproj (which I isn't related, tried nonetheless) with no success. Manually removing/deleting references to `android/google-service.json` and `ios/Runner/GoogleService-Info.plist` did work.

My most recent steps to get things to work.

1. `curl -sL firebase.tools | upgrade=true bash` (I assume npm will also work here)
2. `dart pub global activate flutterfire_cli`
_The above steps are standard, as seen many times over._
3. If the following issue appears below, then delete the google service files found in
    1.  Android: `android/google-service.json`
    2. iOS: `ios/Runner/GoogleService-Info.plist` 
    3. MacOS: `macos/Runner/GoogleService-Info.plist`
    
At this point (assuming no other bugs), all should work as intended.

---

Using:
```
Mac@MacBook-Pro Ucallz % flutterfire configure --project=my-mobile-app --android-package-name=com.my.app --ios-bundle-id=com.my.app --platforms=android,ios -y
```

with output
```
i Found 3 Firebase projects. Selecting project my-mobile-app.                                                                                                                                                                                                                                                                                                
i Selected platforms: android,ios
i Firebase android app com.my.app registered.                                                                                                                                                                                                                                                                                                             
i Firebase ios app com.my.app registered.                                                                                                                                                                                                                                                                                                                 
Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      FirebaseAndroidOptions.projectIdFromFileContents (package:flutterfire_cli/src/firebase/firebase_android_options.dart:29:29)
#5      FirebaseAndroidGradlePlugins.applyGoogleServicesPlugin (package:flutterfire_cli/src/firebase/firebase_android_gradle_plugins.dart:101:50)
<asynchronous suspension>
#6      FirebaseAndroidGradlePlugins.apply (package:flutterfire_cli/src/firebase/firebase_android_gradle_plugins.dart:240:5)
<asynchronous suspension>
```

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel [user-branch], 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-ZA)
    ! Flutter version 3.16.5 on channel [user-branch] at /Users/Mac/.flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 78666c8dc5 (4 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/Mac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Users/Mac/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.216
    ! Error: Browsing on the local area network for Charles’s iPhone (black). Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by cybex-dev** [comment]
from @pablowsky 

> Delete `google-services.json` file and try again

---

If anyone comes across this issue with no prior solution(s) - the quoted solution worked.

I used firebase-tools from `npm`, and standalone installer but neither worked. In installed (updated) xcodeproj (which I isn't related, tried nonetheless) with no success. Manually removing/deleting references to `android/google-service.json` and `ios/Runner/GoogleService-Info.plist` did work.

My most recent steps to get things to work.

1. `curl -sL firebase.tools | upgrade=true bash` (I assume npm will also work here)
2. `dart pub global activate flutterfire_cli`
_The above steps are standard, as seen many times over._
3. If the following issue appears below, then delete the google service files found in
    1.  Android: `android/google-service.json`
    2. iOS: `ios/Runner/GoogleService-Info.plist` 
    3. MacOS: `macos/Runner/GoogleService-Info.plist`
    
At this point (assuming no other bugs), all should work as intended.

---

Using:
```
Mac@MacBook-Pro Ucallz % flutterfire configure --project=my-mobile-app --android-package-name=com.my.app --ios-bundle-id=com.my.app --platforms=android,ios -y
```

with output
```
i Found 3 Firebase projects. Selecting project my-mobile-app.                                                                                                                                                                                                                                                                                                
i Selected platforms: android,ios
i Firebase android app com.my.app registered.                                                                                                                                                                                                                                                                                                             
i Firebase ios app com.my.app registered.                                                                                                                                                                                                                                                                                                                 
Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      FirebaseAndroidOptions.projectIdFromFileContents (package:flutterfire_cli/src/firebase/firebase_android_options.dart:29:29)
#5      FirebaseAndroidGradlePlugins.applyGoogleServicesPlugin (package:flutterfire_cli/src/firebase/firebase_android_gradle_plugins.dart:101:50)
<asynchronous suspension>
#6      FirebaseAndroidGradlePlugins.apply (package:flutterfire_cli/src/firebase/firebase_android_gradle_plugins.dart:240:5)
<asynchronous suspension>
```

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel [user-branch], 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-ZA)
    ! Flutter version 3.16.5 on channel [user-branch] at /Users/Mac/.flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 78666c8dc5 (4 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/Mac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Users/Mac/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.216
    ! Error: Browsing on the local area network for Charles’s iPhone (black). Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by kamil36** [comment]
![image](https://github.com/invertase/flutterfire_cli/assets/53137777/37137061-cf8b-499f-b7fa-87c3022694fb)
