### ISSUE TITLE
flutterfire configure not working 

### ISSUE THREAD

**Issue by PRAJINPRAKASH** [invertase/flutterfire_cli#3]
when running am getting following error 

```
admin>flutterfire configure
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: firebase --version
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:565:18)
#3      Process.run (dart:io-patch/process_patch.dart:47:12)
#4      exists (package:flutterfire_cli/src/firebase.dart:34:33)
#5      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:69:27)
#6      getProjects (package:flutterfire_cli/src/firebase.dart:112:13)
#7      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:159:30)
<asynchronous suspension>
#8      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:225:37)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     main (file:///C:/Users/praji/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.0+2/bin/flutterfire.dart:34:5)
<asynchronous suspension>
```

already have firebase
```
admin> firebase --version
9.23.0
```

**Comment by Salakar** [comment]
What OS are you running the CLI on?
