### ISSUE TITLE
flutterfire configure return an Unhandled exception.

### ISSUE THREAD

**Issue by BLKKKBVSIK** [invertase/flutterfire_cli#37]
I configured a project with `flutterfire configure` a while ago.
Now, the problem is that can't execute the `flutterfire configure` command again.

Even after doing multiple `flutter clean` && removing the `google-service.json` & `google-service.plist`, I'm a still able to execute the command in another flutter project, but not on the one which return me this error.

```
flutterfire configure
Unhandled exception:
Bad state: expecting only one entry for dependency
#0      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:19:9)
#1      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:103:68)
#2      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113:45)
#3      MapMixin.forEach (dart:collection/maps.dart:123:13)
#4      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112:7)
#5      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:103:15)
#6      PubSpec.loadFile (package:pubspec/src/pubspec.dart:121:15)
<asynchronous suspension>
#7      Package.load (package:flutterfire_cli/src/common/package.dart:54:21)
<asynchronous suspension>
#8      FlutterApp.load (package:flutterfire_cli/src/flutter_app.dart:39:21)
<asynchronous suspension>
#9      main (file:///Users/blkkkbvsik/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.1+2/bin/flutterfire.dart:33:24)
<asynchronous suspension>
```

```
flutterfire -v       
0.1.1+2
```

OS:
```
MacOS Monterey 12.0.1 (21A559)
```

**Comment by BLKKKBVSIK** [comment]
Seems like the issue comes from my `pubspec.yaml`:
Specifying a version make the `flutterfire configure` crash.

```
flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
```

**Comment by brunodmn** [comment]
> 

Worked for me!. I commented flutter_localizations and ran `flutterfire configure`...than I uncommented again.
Thanks
