### ISSUE TITLE
[bug]:  0.2.2+1 verseion has Unhandled exception

### ISSUE THREAD

**Issue by JemYKolon** [invertase/flutterfire_cli#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.2+1

### Firebase Tools version

10.7.1

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale
    ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

### Description

I run dart pub global activate flutterfire_cli.

after, below code run

flutterfire configure --project=*
i Found * Firebase projects. Selecting project *.
✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios, macos, web 
i Firebase android app *registered.
i Firebase ios app * registered.
i Firebase macos app * registered.
i Firebase web app *(web) registered.
Unhandled exception:
Null check operator used on a null value
#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:399:36)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#2      main (file:///Users/*/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.2+1/bin/flutterfire.dart:57:5)
<asynchronous suspension>

---

I create new firebase project and retry. but same situation appears.

So, I go "https://pub.dev/packages/flutterfire_cli/versions" and check versions.

I decide previous version run.

And then, it is successful.

### Steps to reproduce

1. dart pub global activate flutterfire_cli
2. flutterfire configure --project=*

but dart pub global activate flutterfire_cli 0.2.2 is successful.

### Expected behavior

0.2.2+1 vs 0.2.2 : check device list is different. 0.2.2+1 shows only active device.(e.g. android/ios/mac/linux < at project create check list) but 0.2.2 shows all devices.(4 + window/etc..)

also 0.2.2 shows me :
✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios, macos, web 
i Firebase android app * registered.
i Firebase ios app * registered.
i Firebase macos app * registered.
i Firebase web app * (web) registered.
? The files android/build.gradle & android/app/build.gradle will be updated to apply Firebase configurat
✔ The files android/build.gradle & android/app/build.gradle will be updated to apply Firebase configuration and gradle build plugins. Do you want to continue? · yes 

Firebase configuration file lib/firebase_options.dart generated successfully with the following Firebase apps:

Platform  Firebase App Id
web      *
android   *
ios       *
macos     *

Learn more about using this file and next steps from the documentation:
 > https://firebase.google.com/docs/flutter/setup

but 0.2.2+1:
✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios, macos, web 
i Firebase android app * registered.
i Firebase ios app * registered.
i Firebase macos app * registered.
i Firebase web app * (web) registered.
Unhandled exception:
Null check operator used on a null value
#0      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:399:36)
<asynchronous suspension>
#1      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#2      main (file:///Users/*/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.2+1/bin/flutterfire.dart:57:5)
<asynchronous suspension>

**Comment by Salakar** [comment]
Fixed in latest version, sorry about that 🙈
