### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by ch3n97w** [invertase/flutterfire_cli#8]
* `flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.5.3, on Arch Linux 5.13.13-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /usr/bin/brave-nightly)
    ! /usr/bin/brave-nightly is not executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2020.2)
[✓] Connected device (2 available)
```

* `flutterfire --version`

```
Precompiling executable... (2.7s)
Failed to precompile flutterfire_cli:flutterfire:
Crash when compiling null,
at character offset null:
Class(TYPEDESC) not found in structCache
#0      new NativeTypeCfe (package:vm/transformations/ffi_definitions.dart:755:9)
#1      _FfiDefinitionTransformer._replaceFields (package:vm/transformations/ffi_definitions.dart:472:16)
#2      _FfiDefinitionTransformer.visitClassInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:197:26)
#3      _FfiDefinitionTransformer.manualVisitInTopologicalOrder.<anonymous closure> (package:vm/transformations/ffi_definitions.dart:160:9)
#4      List.forEach (dart:core-patch/growable_array.dart:403:8)
#5      _FfiDefinitionTransformer.manualVisitInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:136:25)
#6      transformLibraries (package:vm/transformations/ffi_definitions.dart:91:15)
#7      VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:162:34)
#8      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1234:19)
#9      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:372:7)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#13     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#14     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#15     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#16     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#17     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#18     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>


#0      new NativeTypeCfe (package:vm/transformations/ffi_definitions.dart:755:9)
#1      _FfiDefinitionTransformer._replaceFields (package:vm/transformations/ffi_definitions.dart:472:16)
#2      _FfiDefinitionTransformer.visitClassInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:197:26)
#3      _FfiDefinitionTransformer.manualVisitInTopologicalOrder.<anonymous closure> (package:vm/transformations/ffi_definitions.dart:160:9)
#4      List.forEach (dart:core-patch/growable_array.dart:403:8)
#5      _FfiDefinitionTransformer.manualVisitInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:136:25)
#6      transformLibraries (package:vm/transformations/ffi_definitions.dart:91:15)
#7      VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:162:34)
#8      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1234:19)
#9      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:372:7)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#11     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#12     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#13     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#14     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#15     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#16     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:404:11)
<asynchronous suspension>
#17     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:218:45)
<asynchronous suspension>
#18     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:885:37)
<asynchronous suspension>
```

**Comment by Ehesp** [comment]
Where does this error trigger? When installing from pub or running a command?

**Comment by ch3n97w** [comment]
It successfully added in packages, but failed to execute the command(flutterfire configure,flutterfire -v...)

**Comment by justinenerio** [comment]
Was able to solve this issue. The cause was having two versions of dart in path. Uninstalling old dart sdk fixed it. Check if you have installed a previous version of dart. Flutter should have bundled the dart sdk already.

**Comment by ch3n97w** [comment]
Thanks, it works
